import test from "node:test";
import assert from "node:assert/strict";
import { randomBytes, randomUUID } from "node:crypto";
import { DatabaseSync } from "node:sqlite";
import { accessChangeSchema, matchesAllowlist } from "../src/maintenance-access.js";
import { MaintenanceAccessStore } from "../src/maintenance-access-store.js";
import { ServiceStore } from "../src/service-store.js";
import { SessionStore } from "../src/session-store.js";
import { buildApp } from "../src/app.js";
import type { Grant } from "../src/access-policy.js";
test("maintenance IP matching rejects malformed and all-address networks; handles IPv6 and mapped IPv4", () => {
  const input = { mode: "manual", allowlist: [], reason: "maintenance", version: 0, idempotencyKey: randomUUID() };
  for (const ip of ["1.2.3.999", "host.example", "192.0.2.1:80", "0.0.0.0/0", "::/0", "192.0.2.0/33", "::/129", "fe80::1%eth0", "::1/", "::1/1/2", "192.0.2.1; return 200;"]) assert.equal(accessChangeSchema.safeParse({ ...input, allowlist: [ip] }).success, false, ip);
  for (const ip of ["192.0.2.0", "192.0.2.255", "::ffff:192.0.2.10", "::ffff:c000:20a"]) assert.equal(matchesAllowlist(ip, ["192.0.2.0/24"]), true, ip);
  assert.equal(matchesAllowlist("192.0.3.0", ["192.0.2.0/24"]), false);
  assert.equal(matchesAllowlist("2001:db8:0:ffff::1", ["2001:db8::/48"]), true);
  assert.equal(matchesAllowlist("2001:db8:1::1", ["2001:db8::/48"]), false);
  assert.equal(matchesAllowlist("192.0.2.11", ["192.0.2.10"]), false);
  for (const ip of ["", "192.0.2.10, 198.51.100.1", "invalid", "fe80::1%eth0"]) assert.equal(matchesAllowlist(ip, ["192.0.2.0/24"]), false);
});
test("maintenance policy is atomic, persists, deduplicates and preserves newer configuration", (t) => {
  const db = new DatabaseSync(":memory:"); t.after(() => db.close()); db.exec("CREATE TABLE audit_events(id INTEGER PRIMARY KEY,actor TEXT,action TEXT,request_id TEXT,created_at INTEGER)");
  const store = new MaintenanceAccessStore(db); const id = randomUUID(); const input = { mode: "manual" as const, allowlist: ["192.0.2.1"], reason: "test" };
  db.exec("CREATE TRIGGER audit_failure BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'injected'); END");
  assert.throws(() => store.save("site", input, 0, id, "admin", "r")); assert.equal(store.get("site").version, 0);
  db.exec("DROP TRIGGER audit_failure"); store.save("site", input, 0, id, "admin", "r");
  assert.equal(store.save("site", input, 0, id, "admin", "r").version, 1);
  assert.throws(() => store.save("site", input, 0, randomUUID(), "admin", "r"));
  assert.throws(() => store.save("site", input, 0, id, "other", "r"));
  store.save("site", { ...input, mode: "off" }, 1, randomUUID(), "admin", "r");
  assert.equal(store.save("site", input, 0, id, "admin", "r").mode, "off");
  assert.equal(new MaintenanceAccessStore(db).get("site").version, 2);
  assert.equal(db.prepare("SELECT count(*) n FROM audit_events").get()!.n, 2);
});
test("maintenance API enforces admin/environment/origin and authenticated ingress including fail-closed", async (t) => {
  const store = new ServiceStore(":memory:"); const sessions = new SessionStore(":memory:", randomBytes(32));
  const service = store.create(randomUUID(), "local", { name: "site", owner: "ops", targetId: "target", intervalSeconds: 30 }, "ops", "test");
  let role: Grant["role"] = "viewer"; const token = randomBytes(32).toString("hex");
  const app = buildApp({ store: sessions, services: store, maintenanceGate: { serviceId: service.id, token, mode: "demo" }, identity: { verify: async () => ({ userId: "ops", displayName: "Ops", role: "ADMIN" }), ready: async () => true }, policy: async () => ({ environments: [{ id: "local", name: "Local", type: "development" }], grants: [{ userId: "ops", role, environmentIds: ["local"] }] }), origin: "http://localhost:4320", secureCookie: false });
  t.after(async () => { await app.close(); store.close(); sessions.close(); });
  const session = sessions.create("ops", "test-token", "test"); const headers = { origin: "http://localhost:4320", cookie: `mc_health_session=${session.id}` };
  const url = `/api/v1/services/${service.id}/maintenance-access`; const payload = { mode: "manual", allowlist: ["192.0.2.0/24"], reason: "maintenance", version: 0, idempotencyKey: randomUUID() };
  assert.equal((await app.inject({ url })).statusCode, 401);
  for (const next of ["viewer", "operator"] as const) { role = next; assert.equal((await app.inject({ method: "POST", url, headers, payload })).statusCode, 403); }
  role = "admin";
  assert.equal((await app.inject({ method: "POST", url, headers: { ...headers, origin: "http://evil" }, payload })).statusCode, 403);
  assert.equal((await app.inject({ url: "/api/v1/services/unknown/maintenance-access", headers })).statusCode, 404);
  assert.equal((await app.inject({ method: "POST", url, headers, payload: { ...payload, allowlist: ["0.0.0.0/0"] } })).statusCode, 400);
  assert.equal((await app.inject({ method: "POST", url, headers, payload })).statusCode, 200);
  assert.equal((await app.inject({ method: "POST", url, headers, payload })).json().version, 1);
  assert.equal((await app.inject({ url, headers })).json().active, true);
  const gateUrl = "/internal/maintenance-check";
  const gate = (ip: string) => app.inject({ url: gateUrl, headers: { "x-maintenance-key": token, "x-maintenance-ip": ip, "x-forwarded-for": "192.0.2.1" } });
  assert.equal((await app.inject({ url: gateUrl, headers: { "x-maintenance-ip": "192.0.2.1" } })).statusCode, 403);
  assert.equal((await gate("192.0.2.128")).statusCode, 204);
  assert.equal((await gate("198.51.100.1")).statusCode, 403);
  assert.equal((await gate("bad")).statusCode, 403);
  const original = store.maintenanceAccess.get.bind(store.maintenanceAccess); store.maintenanceAccess.get = () => { throw Error("storage offline"); };
  assert.equal((await gate("192.0.2.1")).statusCode, 503); store.maintenanceAccess.get = original;
  assert.equal(store.auditLog.query({ environmentId: "local", from: 0, to: Date.now() + 1, page: 1, category: "maintenance" }).total, 1);
  const off = { ...payload, mode: "off", version: 1, idempotencyKey: randomUUID() };
  await app.inject({ method: "POST", url, headers, payload: off }); assert.equal((await gate("198.51.100.1")).statusCode, 204);
  await app.inject({ method: "POST", url, headers, payload: { ...payload, mode: "window", version: 2, idempotencyKey: randomUUID() } });
  assert.equal((await gate("198.51.100.1")).statusCode, 204);
  const now = Date.now(); const window = store.maintenance.create(randomUUID(), { serviceId: service.id, startsAt: now, endsAt: now + 60000, owner: "ops", reason: "test" }, "ops", "r");
  assert.equal(store.maintenance.active(service.id, now - 1), 0); assert.equal(store.maintenance.active(service.id, now), 1); assert.equal(store.maintenance.active(service.id, now + 60000), 0);
  assert.equal((await gate("198.51.100.1")).statusCode, 403);
  store.maintenance.cancel(window.id, "done", "ops", "r"); assert.equal((await gate("198.51.100.1")).statusCode, 204);
});
