import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID,randomBytes } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { ServiceStore } from '../src/service-store.js';
import { RecoveryManager } from '../src/recovery-manager.js';
import { RecoveryStore } from '../src/recovery-store.js';
import { targetFingerprint } from '../src/probe.js';
import { summarizeContainerErrors,dockerRecoveryExecutor } from '../src/recovery-docker.js';
import { buildApp } from '../src/app.js';
import { SessionStore } from '../src/session-store.js';
import type { Grant } from '../src/access-policy.js';
function fixture(){const store=new ServiceStore(':memory:');const service=store.create(randomUUID(),'local',{name:'site',owner:'ops',targetId:'t',intervalSeconds:30},'admin','r');const target={id:'t',name:'t',environmentId:'local',url:'http://127.0.0.1:4310/health/live',address:'127.0.0.1'};const policy={environments:[{id:'local',name:'Local',type:'development' as const}],grants:[],probeTargets:[target]};const now=Date.now();store.recovery.configure(service.id,true,0,randomUUID(),'admin','approved',now-120000);return{store,service,target,policy,now};}
function failures(c:ReturnType<typeof fixture>,now:number,status=503,actor='system:collector'){let last!:NonNullable<ReturnType<ServiceStore['getProbe']>>;for(const at of [now-60000,now-30000,now]){const id=randomUUID();assert.ok(c.store.claimProbe(c.service,id,targetFingerprint(c.target),actor,'r',at));c.store.finishProbe(id,{outcome:'http_error',httpStatus:status,latencyMs:2},at+1);last=c.store.getProbe(id)!;}return last;}
test('automatic restart claims once after 3 fresh server faults, saves diagnostics before restart, verifies health',async(t)=>{const c=fixture();t.after(()=>c.store.close());let calls=0;const manager=new RecoveryManager(c.service.id,'demo',c.store,async()=>c.policy,{diagnostics:async()=>({available:true,codes:['ECONNRESET']}),restart:async()=>{calls++;assert.deepEqual(c.store.recovery.active()!.diagnostics!.codes,['ECONNRESET']);},healthy:async()=>true});const sample=failures(c,c.now);manager.observe(sample);manager.observe(sample);await manager.settled();assert.equal(calls,1);assert.equal(c.store.recovery.list(c.service.id)[0]!.status,'succeeded');assert.equal(c.store.failureLogs.list(c.service.id,1,c.now+1).total,3);manager.observe(sample);await manager.settled();assert.equal(calls,1);});
test('automatic restart rejects client errors, manual probes, stale samples, maintenance and revoked targets',async(t)=>{for(const scenario of ['client','manual','stale','maintenance','revoked','release'] as const){const c=fixture();let calls=0;const sample=failures(c,c.now,scenario==='client'?404:503,scenario==='manual'?'admin':'system:collector');const manager=new RecoveryManager(c.service.id,'demo',c.store,async()=>({...c.policy,probeTargets:scenario==='revoked'?[]:[c.target]}),{diagnostics:async()=>({available:true,codes:[]}),restart:async()=>{calls++;},healthy:async()=>true});if(scenario==='stale')sample.startedAt-=100000;if(scenario==='maintenance')c.store.maintenance.create(randomUUID(),{serviceId:c.service.id,startsAt:c.now,endsAt:c.now+60000,owner:'ops',reason:'test'},'ops','r',c.now);if(scenario==='release')c.store.releases.create({id:randomUUID(),serviceId:c.service.id,from:'a',to:'b',action:'update',reason:'r',backupReference:'r',actor:'admin',status:'running',message:'r',createdAt:c.now,finishedAt:null});manager.observe(sample);await manager.settled();assert.equal(calls,0,scenario);await manager.close();c.store.close();}});
test('restart cooldown, hourly quota and sample reset persist in store',()=>{const c=fixture();let now=c.now;for(let i=0;i<3;i++){const sample=failures(c,now);const task=c.store.recovery.claim(c.service,sample,targetFingerprint(c.target),now);assert.ok(task);c.store.recovery.finish(task.id,'succeeded','healthy','system',now);assert.equal(c.store.recovery.claim(c.service,sample,targetFingerprint(c.target),now+1),null);now+=661000;}const next=failures(c,now);assert.equal(c.store.recovery.claim(c.service,next,targetFingerprint(c.target),now),null);assert.equal(c.store.recovery.budget(c.service.id,now).attemptsLastHour,3);c.store.close();});
test('uncertain restart locks both restarts and releases until explicitly reconciled; disabled during diagnostics cancels',async()=>{const c=fixture();const sample=failures(c,c.now);const manager=new RecoveryManager(c.service.id,'demo',c.store,async()=>c.policy,{diagnostics:async()=>({available:false,codes:[]}),restart:async()=>{throw Error('private secret');},healthy:async()=>false});manager.observe(sample);await manager.settled();assert.equal(c.store.recovery.active()!.status,'unknown');assert.equal(JSON.stringify(manager.snapshot()).includes('private secret'),false);assert.throws(()=>c.store.releases.create({id:randomUUID(),serviceId:c.service.id,from:'a',to:'b',action:'update',reason:'r',backupReference:'r',actor:'admin',status:'running',message:'r',createdAt:c.now,finishedAt:null}));manager.reconcile('admin',sample.id);manager.reconcile('admin',sample.id);assert.equal(c.store.recovery.active(),null);c.store.close();const d=fixture();let calls=0;const other=new RecoveryManager(d.service.id,'demo',d.store,async()=>d.policy,{diagnostics:async()=>{d.store.recovery.configure(d.service.id,false,1,randomUUID(),'admin','cancel');return{available:true,codes:[]};},restart:async()=>{calls++;},healthy:async()=>true});other.observe(failures(d,d.now));await other.settled();assert.equal(calls,0);assert.equal(d.store.recovery.list(d.service.id)[0]!.status,'canceled');d.store.close();});
test('interrupted recovery becomes unknown on startup; audit failure rolls back policy',()=>{const db=new DatabaseSync(':memory:');db.exec('CREATE TABLE audit_events(id INTEGER PRIMARY KEY,actor TEXT,action TEXT,request_id TEXT,created_at INTEGER)');const store=new RecoveryStore(db);db.exec("CREATE TRIGGER fail_audit BEFORE INSERT ON audit_events BEGIN SELECT RAISE(ABORT,'injected');END");assert.throws(()=>store.configure('s',true,0,randomUUID(),'a','r'));assert.equal(store.policy('s').enabled,false);db.exec('DROP TRIGGER fail_audit');const task={id:'t',serviceId:'s',status:'running',createdAt:Date.now(),finishedAt:null,message:'r',diagnostics:null};db.prepare('INSERT INTO recovery_tasks VALUES (?,?,?,?,?)').run('t','s','running',task.createdAt,JSON.stringify(task));new RecoveryStore(db);assert.equal(store.active()!.status,'unknown');db.close();});
test('container diagnostics retain only recognized codes; restart uses fixed containers and bounded command',async()=>{assert.deepEqual(summarizeContainerErrors('patient=private token=secret TypeError: sensitive\nECONNRESET'),{available:true,codes:['TypeError','ECONNRESET']});const calls:string[][]=[];const executor=dockerRecoveryExecutor(['medicalcare-app'],async(args,timeout)=>{calls.push(args);assert.ok(timeout<=45000);return 'ECONNRESET private payload';});assert.deepEqual((await executor.diagnostics()).codes,['ECONNRESET']);await executor.restart();assert.deepEqual(calls[1],['restart','--time','10','medicalcare-app']);assert.throws(()=>dockerRecoveryExecutor(['postgres' as 'medicalcare-app']));});
test('recovery API enforces roles, origin, version, deployment availability and production simulation denial',async(t)=>{const c=fixture();const sessions=new SessionStore(':memory:',randomBytes(32));let role:Grant['role']='viewer';const manager=new RecoveryManager(c.service.id,'docker',c.store,async()=>c.policy,{diagnostics:async()=>({available:true,codes:[]}),restart:async()=>{},healthy:async()=>true});const app=buildApp({store:sessions,services:c.store,recoveryManager:manager,identity:{ready:async()=>true,verify:async()=>({userId:'ops',displayName:'Ops',role:'ADMIN'})},policy:async()=>({...c.policy,grants:[{userId:'ops',role,environmentIds:['local']}]}),origin:'http://localhost:4320',secureCookie:false});t.after(async()=>{await app.close();await manager.close();sessions.close();c.store.close();});const s=sessions.create('ops','token','r');const headers={origin:'http://localhost:4320',cookie:`mc_health_session=${s.id}`};const url=`/api/v1/services/${c.service.id}/recovery`;const payload={enabled:false,version:1,idempotencyKey:randomUUID(),reason:'disabled'};assert.equal((await app.inject({url})).statusCode,401);for(const r of ['viewer','operator'] as const){role=r;assert.equal((await app.inject({url:url+'/configure',method:'POST',headers,payload})).statusCode,403);}role='admin';assert.equal((await app.inject({url:url+'/configure',method:'POST',headers:{...headers,origin:'http://other'},payload})).statusCode,403);assert.equal((await app.inject({url:url+'/configure',method:'POST',headers,payload})).statusCode,200);assert.equal((await app.inject({url:url+'/configure',method:'POST',headers,payload})).statusCode,200);assert.equal((await app.inject({url:url+'/configure',method:'POST',headers,payload:{...payload,idempotencyKey:randomUUID()}})).statusCode,409);assert.equal((await app.inject({url:url+'/simulate',method:'POST',headers,payload:{idempotencyKey:randomUUID()}})).statusCode,400);assert.equal((await app.inject({url:'/api/v1/services/other/recovery',headers})).statusCode,404);});

import { createServer } from 'node:http';
test('Docker recovery health confirmation probes the approved HTTP endpoint after inspecting containers',async(t)=>{
 const server=createServer((_req,res)=>{res.writeHead(200);res.end('ok');});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise<void>(resolve=>server.close(()=>resolve())));const address=server.address();assert.ok(address&&typeof address==='object');let inspected=false;
 const executor=dockerRecoveryExecutor(['medicalcare-app'],async args=>{if(args[0]==='inspect'){inspected=true;return 'true|healthy';}return '';});
 assert.equal(await executor.healthy({id:'t',name:'t',environmentId:'local',url:`http://127.0.0.1:${address.port}/health`,address:'127.0.0.1'}),true);assert.equal(inspected,true);
});
test('healthy-check failure also locks automatic recovery, even if restart command returned successfully',async()=>{const c=fixture();const manager=new RecoveryManager(c.service.id,'demo',c.store,async()=>c.policy,{diagnostics:async()=>({available:true,codes:[]}),restart:async()=>{},healthy:async()=>false});manager.observe(failures(c,c.now));await manager.settled();assert.equal(c.store.recovery.active()!.status,'unknown');await manager.close();c.store.close();});
